### ISSUE TITLE
代码相关的论文

### ISSUE THREAD

**Issue by lihuan2022** [PengLinzhi/DyGKT#1]
作者您好，请问你的代码有相关论文吗？通读您的代码后，有些不懂之处，网络上也没找到DyGKT论文，如有发表的论文，还请分享一下链接，不胜感激！

**Comment by PengLinzhi** [comment]
您好，我们的论文处于在投状态，可能过段时间会公开。请问您是哪个学校或单位的呢？



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年4月27日(周六) 下午4:29
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [PengLinzhi/DyGKT] 代码相关的论文 (Issue #1)




 
作者您好，请问你的代码有相关论文吗？通读您的代码后，有些不懂之处，网络上也没找到DyGKT论文，如有发表的论文，还请分享一下链接，不胜感激！

**Comment by lihuan2022** [comment]
您好，我是上海师范大学电子信息专硕学生李欢，祝你们的论文投稿顺利～



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年4月27日(周六) 下午5:10
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [PengLinzhi/DyGKT] 代码相关的论文 (Issue #1)




 您好，我们的论文处于在投状态，可能过段时间会公开。请问您是哪个学校或单位的呢？ 
 
 
 
 ---原始邮件--- 
 发件人: ***@***.***&amp;gt; 
 发送时间: 2024年4月27日(周六) 下午4:29 
 收件人: ***@***.***&amp;gt;; 
 抄送: ***@***.***&amp;gt;; 
 主题: [PengLinzhi/DyGKT] 代码相关的论文 (Issue #1) 
 
 
 
 
   
 作者您好，请问你的代码有相关论文吗？通读您的代码后，有些不懂之处，网络上也没找到DyGKT论文，如有发表的论文，还请分享一下链接，不胜感激！
